name: Bandit via test.sh

on: [pull_request]

jobs:
  bandit:
    name: Bandit analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 32
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v1

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: bandit
