name: Run tests using test.sh

on: [pull_request]

jobs:
  test:
    name: Python ${{ matrix.os.python }} tests on ${{ matrix.os.name }}-${{ matrix.os.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 30
            python: 3
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
        run: ./test.sh

      - name: Upload coverage.py data
        uses: actions/upload-artifact@v2
        with:
          path: .coverage
          name: .coverage.${{ matrix.os.name }}_${{ matrix.os.version }}.python${{ matrix.os.python }}

  coverage_py:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Download all coverage.py data
        uses: actions/download-artifact@v2

      - name: Run Coverage.py report
        uses: ben-alkov/actions/coverage-py@coverage-py

  pylint:
    name: Pylint analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: fedora
            version: 29
            python: 2
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v2

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: pylint

  bandit:
    name: Bandit analyzer for Python ${{ matrix.os.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - uses: actions/checkout@v1

      - run: ./test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
          ACTION: bandit
